//Project
export const PROJECT_FORM = "PROJECT_FORM";
export const GET_PROJECTS = "GET_PROJECTS";
export const ADD_PROJECT = "ADD_PROJECT";
export const VALIDATE_FORM = "VALIDATE_FORM";
export const ACTUAL_PROJECT = "ACTUAL_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
//Task
export const TASKS_PROJECT = "TASKS_PROJECT";
export const ADD_TASK = "ADD_TASK";
export const VALIDATE_TASK = "VALIDATE_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const ACTUAL_TASK = "ACTUAL_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const STATUS_TASK = "STATUS_TASK";
//Alert
export const SHOW_ALERT_USER = "SHOW_ALERT_USER"
export const HIDE_ALERT_USER = "HIDE_ALERT_USER"
export const SHOW_ALERT_EMAIL = "SHOW_ALERT_EMAIL"
export const HIDE_ALERT_EMAIL = "HIDE_ALERT_EMAIL"
export const SHOW_ALERT_PASSWORD = "SHOW_ALERT_PASSWORD"
export const HIDE_ALERT_PASSWORD = "HIDE_ALERT_PASSWORD"

export const REGISTER_SUCCESS = "REGISTER_SUCCES"
export const REGISTER_ERROR = "REGISTER_ERROR"
export const GET_USER = "GET_USER"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"
export const SIGN_OUT = "SIGN_OUT"